language: node_js  #设置语言

node_js: stable  #设置相应的版本


# S: Build Lifecycle
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli


install:
  - npm install  #安装hexo及插件
  

before_script:
  - npm install -g gulp
  

script:
  - hexo clean && hexo g
  - gulp default #使用 gulp 对流程进行优化

after_script:
  - cd ./public
  - git init
  - git config user.name "super3h"  #修改name
  - git config user.email "781176645@qq.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - blog-source  #只监测blog-source分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/super3h/super3h.github.io.git  #设置GH_REF，注意更改yourname